version: '3'
services:
  web:
    image: demoapp
    ports:
      - "8080:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    update_config:
      parallelism: 2
      delay: 10s

